openapi: 3.0.0

info:
  title: Insolvency API
  description: API specification for submiting insolvency data
  version: 1.0.0-dev

paths:
  /transaction/{transaction_id}/insolvency:
    post:
      tags:
        - "Insolvency"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: createCase
      summary: Create a new insolvency case
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInsolvencyCase'
      responses:
        201:
          description: Case created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaseCreated'

  /transaction/{transaction_id}/insolvency/liquidator:
    post:
      tags:
        - "Insolvency"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: appointLiquidator
      summary: Appoint a liquidator to this case
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AppointLiquidatorBody'
      responses:
        200:
          description: Liquidator appointed

  /transaction/{transaction_id}:
    put:
      tags:
        - "Transactions"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: closeTransaction
      summary: Close a transaction so that its contents get processed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionPutBody'


components:
  schemas:
    CreateInsolvencyCase:
      type: object
      properties:
        start_date:
          type: string
          format: date

    CaseCreated:
      type: object
      properties:
        id:
          type: string
          format: uuid
        links:
          type: object
          properties:
            case:
              type: string
              format: uri
              example: /transaction/{transaction_id}/insolvency/019a2d58-1d1c-481c-a5c4-a7eed0f92c72

    AppointLiquidatorBody:
      type: object
      properties:
        insolvency_id:
          type: string
        attachments:
          type: array
          items:
            type: string
            format: binary
        liquidator:
          type: object
          properties:
            name:
              type: string
            office_holder_number:
              type: number
            address:
              type: string

    TransactionPutBody:
      type: object
      properties:
        reference:
          type: string
        resume_journey_uri:
          type: string
        status:
          type: string

  
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth2 with the correct grants to allow insolvency data submission
      flows:
        authorizationCode:
          tokenUrl: "https://api.companieshouse.gov.uk/oauth2/token"
          authorizationUrl: "https://api.companieshouse.gov.uk/oauth2/authorize"
          scopes:
            submit_insolvency_data: Submit data
