openapi: 3.0.0

info:
  title: Insolvency API
  description: API specification for submiting insolvency data
  version: 1.0.0-dev

paths:
  /transactions/{transaction_id}/insolvency-cases:
    post:
      tags:
        - "Insolvency"
      parameters:
        - in: path
          name: company_number
          required: true
          description: The company number to create an insolvency case for
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: createCase
      summary: Create a new insolvency case
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInsolvencyCaseRequest'
      responses:
        201:
          description: Case created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateInsolvencyCaseResponse'

  /transactions/{transaction_id}/insolvencies/liquidator:
    post:
      tags:
        - "Insolvency"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: appointLiquidator
      summary: Appoint a liquidator to this case
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AppointLiquidatorRequest'
      responses:
        201:
          description: Liquidator appointment request received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointLiquidatorResponse'

components:
  schemas:
    CreateInsolvencyCaseRequest:
      type: object
      properties:
        start_date:
          type: string
          format: date
        type:
          type: string
          enum: [members-voluntary-liquidation, creditors-voluntary-liquidation]
      required: [type]

    CreateInsolvencyCaseResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 019a2d58-1d1c-481c-a5c4-a7eed0f92c72
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /company/{company_number}/insolvencies/019a2d58-1d1c-481c-a5c4-a7eed0f92c72

    AppointLiquidatorRequest:
      type: object
      properties:
        insolvency_id:
          type: string
        attachments:
          type: array
          items:
            type: string
            format: binary
        liquidator:
          type: object
          properties:
            name:
              type: string
            office_holder_number:
              type: number
            address:
              type: string

    AppointLiquidatorResponse:
      type: object
      properties:
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvencies/liquidator/{liquidator_id}
            attachments:
              type: object
              properties:
                "attachment_id":
                  type: string
                  example: "/transactions/{transaction_id}/insolvencies/liquidator/{liquidator_id}/attachments/{attachment_id}"
  
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth2 with the correct grants to allow insolvency data submission
      flows:
        authorizationCode:
          tokenUrl: "https://api.companieshouse.gov.uk/oauth2/token"
          authorizationUrl: "https://api.companieshouse.gov.uk/oauth2/authorize"
          scopes:
            submit_insolvency_data: Submit data
