openapi: 3.0.0

info:
  title: Insolvency API
  description: API specification for submiting insolvency data
  version: 1.0.0-dev

paths:
  /transactions/{transaction_id}/insolvencies/attachments:
    post:
      tags:
        - "Insolvency"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: submitFileAttachment
      summary: Send a file attchement for the case
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AttachmentRequest'

      responses:
        200:
          description: The file was accepted for processing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttachmentResponse'

  /transactions/{transaction_id}/insolvencies/liquidator:
    post:
      tags:
        - "Insolvency"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: appointLiquidator
      summary: Appoint a liquidator to this case
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointLiquidatorRequest'
      responses:
        201:
          description: Liquidator appointment request received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointLiquidatorResponse'

components:
  schemas:
    AttachmentRequest:
      type: object
      properties:
        attachment_type:
          type: string
          enum:
            - declaration-of-solvency
            - statutory-accounts
        file:
          type: string
          format: binary

    AttachmentResponse:
      type: object
      properties:
        attachment_id:
          type: string
          format: uuid

    AppointLiquidatorRequest:
      type: object
      properties:
        insolvency_id:
          type: string
        attachments:
          type: array
          items:
            type: string
            format: uuid
        liquidator:
          type: object
          properties:
            name:
              type: string
            office_holder_number:
              type: number
            address:
              type: string

    AppointLiquidatorResponse:
      type: object
      properties:
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvencies/liquidator/{liquidator_id}
            attachments:
              type: object
              properties:
                "attachment_id":
                  type: string
                  example: "/transactions/{transaction_id}/insolvencies/liquidator/{liquidator_id}/attachments/{attachment_id}"
  
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth2 with the correct grants to allow insolvency data submission
      flows:
        authorizationCode:
          tokenUrl: "https://api.companieshouse.gov.uk/oauth2/token"
          authorizationUrl: "https://api.companieshouse.gov.uk/oauth2/authorize"
          scopes:
            submit_insolvency_data: Submit data
