openapi: 3.0.0
info:
  title: Insolvency API
  description: API specification for submiting insolvency data
  version: 1.0.0-dev
paths:
  /transactions/{transaction_id}/insolvency-resources:
    post:
      tags:
        - "Insolvency Resources"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: createInsolvencyResource
      summary: Create an insolvency data change resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsolvencyResourceWritable'
      responses:
        201:
          description: The insolvency data change resource was created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsolvencyResource'
                
  /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}:
    get:
      tags:
        - "Insolvency Resources"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
        - in: path
          name: insolvency_resource_id
          required: true
          description: The insolvency data change resource unique reference
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: getInsolvencyResourceData
      summary: Get insolvency data change resource
      responses:
        200:
          description: The insolvency case data change resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsolvencyResource'

  /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/attachments:
    post:
      tags:
        - "Attachments"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
        - in: path
          name: insolvency_resource_id
          required: true
          description: The insolvency data change resource unique reference
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: submitFileAttachment
      summary: Send a file attchement for the case
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AttachmentWritable'
      responses:
        200:
          description: The file was accepted for processing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attachment'

  /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/attachments/{attachment_id}:
    parameters:
      - in: path
        name: transaction_id
        required: true
        description: The transaction unique reference
        schema:
          type: string
      - in: path
        name: insolvency_resource_id
        required: true
        description: The insolvency data change resource unique reference
        schema:
          type: string
      - in: path
        name: attachment_id
        required: true
        description: The unique attachment id
        schema:
          type: string 
    get:
      tags:
        - "Attachments"
      security:
        - oauth2: [submit_insolvency_data]
      operationId: getAttachment
      summary: Get information about the attachment that was submitted
      responses:
        200:
          description: the attachment resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attachment'
  
    delete:
      tags:
        - "Attachments"
      security:
        - oauth2: [submit_insolvency_data]
      operationId: deleteAttachment
      summary: Delete an attachment from this transaction
      responses:
        204:
          description: The attachment was deleted

  /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/attachments/{attachment_id}/download:
    parameters:
      - in: path
        name: transaction_id
        required: true
        description: The transaction unique reference
        schema:
          type: string
      - in: path
        name: insolvency_resource_id
        required: true
        description: The insolvency data change resource unique reference
        schema:
          type: string
      - in: path
        name: attachment_id
        required: true
        description: The unique attachment id
        schema:
          type: string
    get:
      tags:
        - "Attachments"
      security:
        - oauth2: [submit_insolvency_data]
      operationId: downloadAttachment
      summary: Download the attachment
      responses:
        200:
          description: The file will begin to download
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            image/*:
              schema:
                type: string
                format: binary

  /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/liquidators:
    post:
      tags:
        - "Liquidator"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
        - in: path
          name: insolvency_resource_id
          required: true
          description: The insolvency data change resource unique reference
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: createLiquidator
      summary: Create a liquidator for this insolvency resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LiquidatorWritable'
      responses:
        200:
          description: Liquidator created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Liquidator'

  /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/liquidators/{liquidator_id}:
    get:
      tags:
        - "Liquidator"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
        - in: path
          name: insolvency_resource_id
          required: true
          description: The insolvency data change resource unique reference
          schema:
            type: string
        - in: path
          name: liquidator_id
          required: true
          description: The unique liquidator id
          schema:
            type: string
            format: uuid
      security:
        - oauth2: [submit_insolvency_data]
      operationId: getLiquidator
      summary: Get the liquidator resource
      responses:
        200:
          description: The liquidator resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Liquidator'
          
    delete:
      tags:
        - "Liquidator"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
        - in: path
          name: insolvency_resource_id
          required: true
          description: The insolvency data change resource unique reference
          schema:
            type: string
        - in: path
          name: liquidator_id
          required: true
          description: The unique liquidator id
          schema:
            type: string
            format: uuid
      security:
        - oauth2: [submit_insolvency_data]
      operationId: deleteLiquidator
      summary: Delete the liquidator from this insolvency resource
      responses:
        204:
          description: The liquidator was deleted

  /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/statements-of-affairs:
    post:
      tags:
        - "Statement of Affairs"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
        - in: path
          name: insolvency_resource_id
          required: true
          description: The insolvency data change resource unique reference
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: createStatementOfAffairs
      summary: Create notice of statement of affairs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatementOfAffairsWritable'
      responses:
        200:
          description: Statement of affairs created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatementOfAffairs'

  /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/statements-of-affairs/{statement_id}:
    get:
      tags:
        - "Statement of Affairs"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
        - in: path
          name: insolvency_resource_id
          required: true
          description: The insolvency data change resource unique reference
          schema:
            type: string
        - in: path
          name: statement_id
          required: true
          description: the id of the statement of affairs
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: getStatementOfAffairs
      summary: Get the statement of affairs resource
      responses:
        200:
          description: the statement of affairs resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatementOfAffairs'
  
    delete:
      tags:
        - "Statement of Affairs"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
        - in: path
          name: insolvency_resource_id
          required: true
          description: The insolvency data change resource unique reference
          schema:
            type: string
        - in: path
          name: statement_id
          required: true
          description: the id of the statement of affairs
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: deleteStatementOfAffairs
      summary: Delete the statement of affairs resource
      responses:
        204:
          description: the statement of affairs was deleted
      
components:
  schemas:
    InsolvencyResourceWritable:
      type: object
      properties:
        company_number:
          type: string
        case_type:
          type: string
          enum:
            - members-voluntary-liquidation
            - creditors-voluntary-liquidation
    
    InsolvencyResource:
      type: object
      properties:
        company_number:
          type: string
        case_type:
          type: string
          enum:
            - members-voluntary-liquidation
            - creditors-voluntary-liquidation
        etag:
          type: string
        kind:
          type: string
          enum:
            - insolvency-resource#insolvency-resource
        company_name:
          type: string
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}
            transaction:
              type: string
              format: uri
              example: /transactions/{transaction_id}
            validation_status:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/validation-status
        liquidators:
          type: object
          properties:
            <key>:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/liquidators/{liquidator_id}
        attachments:
          type: object
          properties:
            <key>:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/attachments/{attachment_id}
    Address:
      type: object
      properties:
        address_line_1:
          type: string
        address_line_2:
          type: string
        country:
          type: string
        locality:
          type: string
        region:
          type: string
        postal_code:
          type: string
  
    AttachmentContextTypes:
      type: string
      enum:
         - special-resolution
         - statement-of-affairs-liquidator
         - statement-of-affairs-director
         - statement-of-concurrence
    AttachmentWritable:
      type: object
      properties:
        attachment_type:
          $ref: '#/components/schemas/AttachmentContextTypes'
        file:
          type: string
          format: binary
    Attachment:
      type: object
      properties:
        attachment_type:
          $ref: '#/components/schemas/AttachmentContextTypes'
        file:
          type: object
          properties:
            name:
              type: string
              example: Statement.pdf
            size:
              type: number
              example: 1024
            content_type:
              type: string
              example: application/pdf
        etag:
          type: string
        kind:
          type: string
          example: insolvency-resources#attachment
        status:
          type: string
          enum:
            - submitted
            - processed
            - integrity-failed
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency/attachment/{attachment_id}
            download:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency/attachment/{attachment_id}/download
    LiquidatorWritable:
      type: object
      properties:
        appointed_on:
          type: string
          format: date
        ip_code:
          type: string
        name:
          type: string
        address:
          type: object
          $ref: '#/components/schemas/Address'
        email:
          type: string
          format: email
        telephone_number:
          type: string
        role:
          type: string
          enum:
            - final-liquidator
            - receiver
            - receiver-manager
            - proposed-liquidator
            - provisional-liquidator
            - administrative-receiver
            - practitioner
            - interim-liquidator
  
    Liquidator:
      type: object
      properties:
        appointed_on:
          type: string
          format: date
        ip_code:
          type: string
        name:
          type: string
        address:
          type: object
          $ref: '#/components/schemas/Address'
        email:
          type: string
          format: email
        telephone_number:
          type: string
        role:
          type: string
          enum:
            - final-liquidator
            - receiver
            - receiver-manager
            - proposed-liquidator
            - provisional-liquidator
            - administrative-receiver
            - practitioner
            - interim-liquidator
        etag:
          type: string
        kind:
          type: string
          enum:
            - insolvency-resource#liquidator
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/liquidator/{liquidator_id}
  
    StatementOfAffairsWritable:
      type: object
      properties:
        presenter:
          type: object
          properties:
            name:
              type: string
            address:
              $ref: '#/components/schemas/Address'
            telephone_number:
              type: string
        statement_date:
          type: string
          format: date
  
    StatementOfAffairs:
      type: object
      properties:
        presenter:
          type: object
          properties:
            name:
              type: string
            address:
              $ref: '#/components/schemas/Address'
            telephone_number:
              type: string
        statement_date:
          type: string
          format: date
        etag:
          type: string
        kind:
          type: string
          enum:
            - insolvency-resource#statement-of-affairs
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency-resources/{insolvency_resource_id}/statement-of-affairs/{statement_id}
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth2 with the correct grants to allow insolvency data submission
      flows:
        authorizationCode:
          tokenUrl: "https://api.companieshouse.gov.uk/oauth2/token"
          authorizationUrl: "https://api.companieshouse.gov.uk/oauth2/authorize"
          scopes:
            submit_insolvency_data: Submit data