openapi: 3.0.0

info:
  title: Insolvency API
  description: API specification for submiting insolvency data
  version: 1.0.0-dev

paths:
  /transactions/{transaction_id}/insolvency/attachment:
    post:
      tags:
        - "Attachments"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: submitFileAttachment
      summary: Send a file attchement for the case
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AttachmentRequest'

      responses:
        200:
          description: The file was accepted for processing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttachmentResponse'

  /transactions/{transaction_id}/insolvency/attachment/{attachment_id}:
    parameters:
      - in: path
        name: transaction_id
        required: true
        description: The transaction unique reference
        schema:
          type: string
      - in: path
        name: attachment_id
        required: true
        description: The unique attachment id
        schema:
          type: string 
    get:
      tags:
        - "Attachments"
      security:
        - oauth2: [submit_insolvency_data]
      operationId: getAttachment
      summary: Get information about the attachment that was submitted
      responses:
        200:
          description: the attachment resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttachmentResourceResponse'
      
    delete:
      tags:
        - "Attachments"
      security:
        - oauth2: [submit_insolvency_data]
      operationId: deleteAttachment
      summary: Delete an attachment from this transaction
      responses:
        200:
          description: The attachment was deleted

  /transactions/{transaction_id}/insolvency/attachment/{attachment_id}/download:
    parameters:
      - in: path
        name: transaction_id
        required: true
        description: The transaction unique reference
        schema:
          type: string
      - in: path
        name: attachment_id
        required: true
        description: The unique attachment id
        schema:
          type: string
    get:
      tags:
        - "Attachments"
      security:
        - oauth2: [submit_insolvency_data]
      operationId: downloadAttachment
      summary: Download the attachment
      responses:
        200:
          description: The file will begin to download
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            image/*:
              schema:
                type: string
                format: binary

  /transactions/{transaction_id}/insolvency/liquidator:
    post:
      tags:
        - "Liquidator"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: appointLiquidator
      summary: Appoint a liquidator to this case
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointLiquidatorRequest'
      responses:
        200:
          description: Liquidator appointment request received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointLiquidatorResponse'

  /transactions/{transaction_id}/insolvency/liquidator/{id}:
    delete:
      tags:
        - "Liquidator"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction that this insolvency case is applied to
          schema:
            type: string
        - in: path
          name: id
          required: true
          description: The unique liquidator appointment id
          schema:
            type: string
            format: uuid
      security:
        - oauth2: [submit_insolvency_data]
      operationId: deleteAppointment
      summary: Delete the appointment of liquidator from this transaction
      responses:
        200:
          description: The appointment was deleted

  /transactions/{transaction_id}/insolvency/statement-of-affairs:
    post:
      tags:
        - "Statement of Affairs"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: statementOfAffairs
      summary: Notice of statement of affairs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatementOfAffairsRequest'
      responses:
        200:
          description: Statement of affairs submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatementOfAffairsResponse'

  /transactions/{transaction_id}/insolvency/statement-of-affairs/{statement_id}:
    delete:
      tags:
        - "Statement of Affairs"
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: The transaction unique reference
          schema:
            type: string
        - in: path
          name: statement_id
          required: true
          description: the id of the statement submitted in this transaction
          schema:
            type: string
      security:
        - oauth2: [submit_insolvency_data]
      operationId: deleteStatementOfAffairs
      summary: Delete the statement of affairs from this transaction
      responses:
        200:
          description: the statement of affairs and its attachments have been removed from this transaction
      
components:
  schemas:
    Liquidator:
      type: object
      properties:
        ip_code:
          type: string
        name:
          type: string
        address:
          type: object
          $ref: '#/components/schemas/Address'
        email:
          type: string
          format: email
        telephone_number:
          type: string
        role:
          type: string
          enum:
            - final-liquidator
            - receiver
            - receiver-manager
            - proposed-liquidator
            - provisional-liquidator
            - administrative-receiver
            - practitioner
            - interim-liquidator

    Address:
      type: object
      properties:
        address_line_1:
          type: string
        address_line_2:
          type: string
        country:
          type: string
        locality:
          type: string
        region:
          type: string
        postal_code:
          type: string
        

    StatementOfAffairsRequest:
      type: object
      properties:
        presenter:
          type: object
          properties:
            name:
              type: string
            company_name:
              type: string
            address:
              $ref: '#/components/schemas/Address'
            telephone_number:
              type: string
        statement_date:
          type: string
          format: date
        liquidators:
          type: array
          items:
            $ref: '#/components/schemas/Liquidator'
        attachments:
          type: array
          items:
            type: string
            format: uuid

    StatementOfAffairsResponse:
      type: object
      properties:
        statement_id:
          type: string
          format: uuid
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency/statement-of-affairs/{statement_id}
  
    AttachmentContextTypes:
      type: string
      enum:
         - special-resolution
         - statement-of-affairs-liquidator
         - statement-of-affairs-director
         - statement-of-concurrence

    AttachmentRequest:
      type: object
      properties:
        attachment_type:
          $ref: '#/components/schemas/AttachmentContextTypes'
        file:
          type: string
          format: binary

    AttachmentResponse:
      type: object
      properties:
        attachment_id:
          type: string
          format: uuid
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency/attachment/{attachment_id}

    AttachmentResourceResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - submitted
            - processed
            - integrity-failed
        attachment_type:
          $ref: '#/components/schemas/AttachmentContextTypes'
        file:
          type: object
          properties:
            name:
              type: string
              example: Statement.pdf
            size:
              type: number
              example: 1024
            content_type:
              type: string
              example: application/pdf
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency/attachment/{attachment_id}
            download:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency/attachment/{attachment_id}/download

    AppointLiquidatorRequest:
      type: object
      properties:
        company_name:
          type: string
        case_type:
          type: string
          enum:
            - members-voluntary-liquidation
            - creditors-voluntary-liquidation
        appointed_on:
          type: string
          format: date
        liquidators:
          type: array
          items:
            $ref: '#/components/schemas/Liquidator'

    AppointLiquidatorResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        links:
          type: object
          properties:
            self:
              type: string
              format: uri
              example: /transactions/{transaction_id}/insolvency/liquidator/{id}
  
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth2 with the correct grants to allow insolvency data submission
      flows:
        authorizationCode:
          tokenUrl: "https://api.companieshouse.gov.uk/oauth2/token"
          authorizationUrl: "https://api.companieshouse.gov.uk/oauth2/authorize"
          scopes:
            submit_insolvency_data: Submit data
