version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - "./apispec:/apispec"
    environment:
      - SWAGGER_JSON=/apispec/schema.yml

  insolvency-api:
    image: 169942020521.dkr.ecr.eu-west-1.amazonaws.com/local/insolvency-api
    ports:
      - "3055:3055"
    dockerfile: .
    